import type { OwnerSubscriber } from '../types/ownerSubscriptionPlan';

/**
 * Demo subscribers for the owner UI. Linked loosely by plan name when plan ids
 * from the mock create flow won't match — list/detail remaps onto current plans.
 */
export const MOCK_OWNER_SUBSCRIBERS: OwnerSubscriber[] = [
  {
    id: 'sub-1',
    customerName: 'Maya Chen',
    email: 'maya.chen@email.com',
    phone: '(512) 555-0142',
    planId: 'placeholder',
    planName: 'Exterior Wash',
    visitDurationMinutes: 60,
    cadenceLabel: 'Every 2 weeks',
    intervalUnit: 'week',
    intervalCount: 2,
    amountCents: 7900,
    status: 'active',
    startedAt: '2026-06-12',
    nextBillingAt: '2026-08-21',
    lastPaymentLabel: 'Paid Aug 7',
    paymentMethodLabel: 'Visa ••4242',
    notes: 'Prefers Saturdays around 8am',
    visitStatus: 'needs_visit',
  },
  {
    id: 'sub-2',
    customerName: 'Jordan Lee',
    email: 'jordan.lee@email.com',
    phone: '(737) 555-0198',
    planId: 'placeholder',
    planName: 'Exterior Wash',
    visitDurationMinutes: 60,
    cadenceLabel: 'Weekly',
    intervalUnit: 'week',
    intervalCount: 1,
    amountCents: 4500,
    status: 'active',
    startedAt: '2026-07-01',
    nextBillingAt: '2026-08-14',
    cancelAtPeriodEnd: true,
    lastPaymentLabel: 'Paid Aug 7',
    paymentMethodLabel: 'Mastercard ••4444',
    visitStatus: 'scheduled',
    periodVisitBookingId: 'booking-mock-2',
    periodVisitDate: '2026-08-14',
    periodVisitTime: '09:00',
  },
  {
    id: 'sub-3',
    customerName: 'Sam Rivera',
    email: 'sam.r@email.com',
    phone: '(210) 555-0177',
    planId: 'placeholder',
    planName: 'Premium Detail',
    visitDurationMinutes: 120,
    cadenceLabel: 'Monthly',
    intervalUnit: 'month',
    intervalCount: 1,
    amountCents: 14900,
    status: 'past_due',
    startedAt: '2026-05-20',
    nextBillingAt: '2026-08-05',
    lastPaymentLabel: 'Failed Aug 5',
    paymentMethodLabel: 'Visa ••1881',
    visitStatus: 'needs_visit',
  },
  {
    id: 'sub-4',
    customerName: 'Alex Kim',
    email: 'alex.kim@email.com',
    planId: 'placeholder',
    planName: 'Exterior Wash',
    visitDurationMinutes: 60,
    cadenceLabel: 'Monthly',
    intervalUnit: 'month',
    intervalCount: 1,
    amountCents: 12900,
    status: 'canceled',
    startedAt: '2026-03-10',
    nextBillingAt: null,
    lastPaymentLabel: 'Paid Jul 10',
    paymentMethodLabel: 'Visa ••4242',
    visitStatus: 'none',
  },
];
