export { ProPaymentsSetupExperience } from './ProPaymentsSetupExperience';
export {
  PAYMENTS_PAGE_DESCRIPTION_SETUP_PENDING,
  PAYMENTS_SETUP_BENEFITS,
  PAYMENTS_SETUP_CTA_CONNECT_STRIPE,
  PAYMENTS_SETUP_CTA_CONTINUE_STRIPE,
  PAYMENTS_SETUP_HERO_TITLE,
  PAYMENTS_SETUP_LEAD,
  PAYMENTS_SETUP_TEASE_OVERLINE,
} from './paymentsSetupCopy';
