import type { CustomerRecord } from './types';

export const MOCK_CUSTOMERS: CustomerRecord[] = [
  {
    id: 'cust-001',
    name: 'Sofia Martinez',
    phone: '(813) 555-1092',
    email: 'sofia.m@example.com',
    lastService: 'Deep House Cleaning',
    lastBookingAddOns: ['Inside oven', 'Interior windows'],
    lastBookingDate: '2026-03-18',
    lastBookingDaysAgo: 92,
    totalVisits: 6,
    totalSpent: 860,
    status: 'returning',
    note: 'Prefers Saturday mornings. Interested in quarterly package deals.',
  },
  {
    id: 'cust-002',
    name: 'Jordan Lee',
    phone: '(813) 555-3021',
    email: 'jordan.lee@example.com',
    lastService: 'Lawn Maintenance',
    lastBookingDate: '2026-03-12',
    lastBookingDaysAgo: 98,
    totalVisits: 3,
    totalSpent: 270,
    status: 'returning',
    note: 'Usually rebooks every 4 weeks.',
  },
  {
    id: 'cust-003',
    name: 'Monica Patel',
    phone: '(813) 555-7754',
    email: 'monica.p@example.com',
    lastService: 'HVAC Inspection',
    lastBookingDate: '2026-03-09',
    lastBookingDaysAgo: 101,
    totalVisits: 1,
    totalSpent: 145,
    status: 'new',
    note: 'Requested follow-up quote for filter replacement.',
  },
  {
    id: 'cust-004',
    name: 'Ethan Brooks',
    phone: '(813) 555-4420',
    email: 'ethan.b@example.com',
    lastService: 'Exterior Pressure Wash',
    lastBookingAddOns: ['Driveway & walkway', 'Deck wash'],
    lastBookingDate: '2026-02-28',
    lastBookingDaysAgo: 110,
    totalVisits: 4,
    totalSpent: 510,
    status: 'returning',
    note: 'Best contact time is after 5 PM.',
  },
  {
    id: 'cust-005',
    name: 'Ariana Gomez',
    phone: '(813) 555-8890',
    email: 'ariana.g@example.com',
    lastService: 'Bridal Makeup Trial',
    lastBookingAddOns: ['Lash application'],
    lastBookingDate: '2026-02-22',
    lastBookingDaysAgo: 116,
    totalVisits: 8,
    totalSpent: 1240,
    status: 'returning',
    note: 'High referral potential; sent 2 new leads last month.',
  },
  {
    id: 'cust-006',
    name: 'Noah Kim',
    phone: '(813) 555-6613',
    email: 'noah.k@example.com',
    lastService: 'Auto Detail - Interior',
    lastBookingDate: '2026-02-19',
    lastBookingDaysAgo: 119,
    totalVisits: 2,
    totalSpent: 220,
    status: 'new',
    note: 'Asked about add-on ceramic coating next visit.',
  },
];
